import { describe, it, expect } from "vitest";
import { RELIC_POOL, rollRelic, RELIC_RARITY_WEIGHT } from "../data";
import type { Relic } from "../types";

describe("Relic System", () => {
  describe("RELIC_POOL", () => {
    it("should have exactly 14 relics", () => {
      expect(RELIC_POOL.length).toBe(14);
    });

    it("should have 5 common relics", () => {
      const common = RELIC_POOL.filter((r) => r.rarity === "common");
      expect(common.length).toBe(5);
    });

    it("should have 6 rare relics", () => {
      const rare = RELIC_POOL.filter((r) => r.rarity === "rare");
      expect(rare.length).toBe(6);
    });

    it("should have 3 legendary relics", () => {
      const legendary = RELIC_POOL.filter((r) => r.rarity === "legendary");
      expect(legendary.length).toBe(3);
    });

    it("each relic should have valid id, name, desc, rarity, effects", () => {
      for (const relic of RELIC_POOL) {
        expect(relic.id).toBeTruthy();
        expect(relic.name).toBeTruthy();
        expect(relic.desc).toBeTruthy();
        expect(relic.rarity).toMatch(/^(common|rare|legendary)$/);
        expect(relic.effects).toBeDefined();
        expect(typeof relic.effects).toBe("object");
      }
    });

    it("each relic should have at least one non-zero effect", () => {
      for (const relic of RELIC_POOL) {
        const effects = relic.effects;
        const hasEffect = Object.values(effects).some((v) => v !== undefined && v !== 0);
        expect(hasEffect).toBe(true);
      }
    });

    it("all relic ids should be unique", () => {
      const ids = RELIC_POOL.map((r) => r.id);
      const uniqueIds = new Set(ids);
      expect(uniqueIds.size).toBe(ids.length);
    });
  });

  describe("RELIC_RARITY_WEIGHT", () => {
    it("should export common, rare, legendary weights", () => {
      expect(RELIC_RARITY_WEIGHT.common).toBe(70);
      expect(RELIC_RARITY_WEIGHT.rare).toBe(25);
      expect(RELIC_RARITY_WEIGHT.legendary).toBe(5);
    });

    it("weights should sum to 100", () => {
      const sum =
        RELIC_RARITY_WEIGHT.common +
        RELIC_RARITY_WEIGHT.rare +
        RELIC_RARITY_WEIGHT.legendary;
      expect(sum).toBe(100);
    });
  });

  describe("rollRelic()", () => {
    // Use a seeded random approach - run many times to verify distribution
    it("should return a valid Relic from the pool", () => {
      const relic = rollRelic(1);
      expect(RELIC_POOL.find((r) => r.id === relic.id)).toBeDefined();
    });

    it("should return a Relic with correct structure", () => {
      const relic = rollRelic(1);
      expect(relic.id).toBeTruthy();
      expect(relic.name).toBeTruthy();
      expect(relic.desc).toBeTruthy();
      expect(relic.rarity).toMatch(/^(common|rare|legendary)$/);
      expect(relic.effects).toBeDefined();
    });

    it("should mostly return common relics on wave 1 (statistical)", () => {
      // Run 1000 times and count - should be ~70% common
      const counts = { common: 0, rare: 0, legendary: 0 };
      for (let i = 0; i < 1000; i++) {
        const relic = rollRelic(1);
        counts[relic.rarity]++;
      }
      // Common should be around 700 (70%), allow ±10%
      expect(counts.common).toBeGreaterThan(600);
      expect(counts.common).toBeLessThan(800);
    });

    it("should allow legendary on boss wave (wave 5)", () => {
      // Run 1000 times on wave 5 (boss) - legendary weight is 20 (not 5)
      let gotLegendary = false;
      for (let i = 0; i < 100 && !gotLegendary; i++) {
        const relic = rollRelic(5);
        if (relic.rarity === "legendary") gotLegendary = true;
      }
      // With 20% legendary weight on boss, should get at least one in 100 tries
      expect(gotLegendary).toBe(true);
    });

    it("boss wave should have higher legendary chance than normal wave", () => {
      // Count legendaries on boss wave vs normal wave
      let bossLegendaries = 0;
      let normalLegendaries = 0;
      for (let i = 0; i < 1000; i++) {
        if (rollRelic(5).rarity === "legendary") bossLegendaries++;
        if (rollRelic(1).rarity === "legendary") normalLegendaries++;
      }
      // Boss should have significantly more legendaries
      expect(bossLegendaries).toBeGreaterThan(normalLegendaries);
    });

    it("returned relic should have pool id (unique id is generated by winWave)", () => {
      // rollRelic returns relics with their original pool ids
      // winWave generates unique id: { ...rolled, id: `rel_${...}` }
      const relic1 = rollRelic(1);
      const relic2 = rollRelic(1);
      expect(relic1.id).toBeTruthy();
      expect(relic2.id).toBeTruthy();
    });

    it("should respect rarity distribution (statistical)", () => {
      const counts = { common: 0, rare: 0, legendary: 0 };
      for (let i = 0; i < 1000; i++) {
        const relic = rollRelic(1);
        counts[relic.rarity]++;
      }
      // With weights 70/25/5, each should be within ±15% of expected
      expect(counts.common).toBeGreaterThan(550);  // >55%
      expect(counts.rare).toBeGreaterThan(100);    // >10%
      expect(counts.legendary).toBeLessThan(80);    // <8%
    });
  });
});
